[build]
  base = "api_ul/client/"
  command = "npm run build"
  publish = "dist/" 
  functions = "api_ul/client/netlify/functions" # Keep this if you have functions

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200